# Generated by Django 5.2.14 on 2026-05-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_preferred_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='core.course'),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='recommended_courses',
            field=models.ManyToManyField(blank=True, to='core.course'),
        ),
    ]
